AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Notification Lambda for MS Teams

  This lambda will notify a teams channel when a certain cloudwatch event or SNS message is generated.

Parameters:
  WebHookParam:
    Type: AWS::SSM::Parameter::Value<String>
    Default: TeamsChannel


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  MSTeamsNotifications:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: msteamsnotification/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          MSTEAMS_WEBHOOK_URL: !Ref WebHookParam
      Events:
        AWSHealthEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
              - aws.health
        SigninEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - AWS Console Sign In via CloudTrail
Outputs:
  MSTeamsNotifications:
    Description: "AWS Health Event to MS Teams Function ARN"
    Value: !GetAtt MSTeamsNotifications.Arn
  MSTeamsNotificationsIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt MSTeamsNotificationsRole.Arn
